spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver

endpoints: 
  shutdown: 
    sensitive: false
    enabled: true   
  health: 
    sensitive: false
    enabled: true    
  info: 
    sensitive: false
    enabled: true    
  metrics: 
    sensitive: false
    enabled: true
  trace: 
    sensitive: false
    enabled: true
  env: 
    sensitive: false
    enabled: true
  configprops:   
    sensitive: false
    enabled: true
  jolokia:   
    sensitive: false
    enabled: true
